# This file was generated by GoReleaser. DO NOT EDIT.
cask "ptop" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "de6f7987a2af791ffe2e0ec7a72920b9d900aeec6a771cc2a5df7716417cd219"
      url "https://github.com/trentas/ptop/releases/download/v#{version}/ptop-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "be6945152c772f4130c207984911443f49c6a4b45968b8adf57fcdf5a6ba2fb0"
      url "https://github.com/trentas/ptop/releases/download/v#{version}/ptop-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b60986eeb3adf91a7a311487227367022cfcac1cfbbe690c3dce830c601e2c78"
      url "https://github.com/trentas/ptop/releases/download/v#{version}/ptop-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "7477635fe3449ef1592d432f8633a8c10f564c21f6f2de9c1decff49abedb504"
      url "https://github.com/trentas/ptop/releases/download/v#{version}/ptop-#{version}-linux-arm64.tar.gz"
    end
  end

  name "ptop"
  desc "Interactive TUI for deep inspection of Linux processes via eBPF"
  homepage "https://github.com/trentas/ptop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ptop"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run as root: sudo ptop -pid <PID>

    On Linux, all panels are backed by eBPF. On macOS, collectors fall back
    to libproc + Mach ("Tier 1"): syscalls (F2), per-file I/O latency (F5)
    and the lock graph (F7) have no kernel equivalent and stay empty. ptop
    prints which tier it is running in on startup.
  EOS
end
