# This file was generated by GoReleaser. DO NOT EDIT.
cask "ptop" do
  version "1.7.2"

  on_macos do
    on_arm do
      sha256 "1d586ee6e07db197a51c02e655042cba73d853a2a4e04303a7cb4404b830c88b"
      url "https://github.com/trentas/ptop/releases/download/v#{version}/ptop-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "889236128539e0aa1953204be2463171c0f87218ba0f4458af381f735bac2018"
      url "https://github.com/trentas/ptop/releases/download/v#{version}/ptop-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fb4b8c49996c66a3f920383518c88ec38a5b1854c7e04b68dab3cc533a02bab3"
      url "https://github.com/trentas/ptop/releases/download/v#{version}/ptop-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "f676226032b60e28d133647dd055aedb42e644ee01961601efbe0b095d707d80"
      url "https://github.com/trentas/ptop/releases/download/v#{version}/ptop-#{version}-linux-amd64.tar.gz"
    end
  end

  name "ptop"
  desc "Interactive TUI for deep inspection of Linux processes via eBPF"
  homepage "https://github.com/trentas/ptop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ptop"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run as root: sudo ptop -pid <PID>

    On Linux, all panels are backed by eBPF. On macOS, collectors fall back
    to libproc + Mach ("Tier 1"): syscalls (F2), per-file I/O latency (F5)
    and the lock graph (F7) have no kernel equivalent and stay empty. ptop
    prints which tier it is running in on startup.
  EOS
end
