# This file was generated by GoReleaser. DO NOT EDIT.
cask "ptop" do
  version "1.7.1"

  on_macos do
    on_arm do
      sha256 "67e1656380819fa901bdbba110e8e816c1cba81e0b93297432fe0860162d06c7"
      url "https://github.com/trentas/ptop/releases/download/v#{version}/ptop-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "a670439e2c1e3ad20c05c5317d04d2d925268421b9f0701ae1e2bf8f3b4442d8"
      url "https://github.com/trentas/ptop/releases/download/v#{version}/ptop-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bc447d7d16fa47c9e2246fd67b14a753777ba50e709f58d0e035aadf1336e00c"
      url "https://github.com/trentas/ptop/releases/download/v#{version}/ptop-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "5dfe3b2d744f03d0262c7803719da13c6dfaa10eef09ac00906373059598e59c"
      url "https://github.com/trentas/ptop/releases/download/v#{version}/ptop-#{version}-linux-amd64.tar.gz"
    end
  end

  name "ptop"
  desc "Interactive TUI for deep inspection of Linux processes via eBPF"
  homepage "https://github.com/trentas/ptop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ptop"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run as root: sudo ptop -pid <PID>

    On Linux, all panels are backed by eBPF. On macOS, collectors fall back
    to libproc + Mach ("Tier 1"): syscalls (F2), per-file I/O latency (F5)
    and the lock graph (F7) have no kernel equivalent and stay empty. ptop
    prints which tier it is running in on startup.
  EOS
end
