# This file was generated by GoReleaser. DO NOT EDIT.
cask "vmstat-macos" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "a51d074c923bfaf6b147867c31ea29f35f597778d4f31b7ac80bf9dd81be2c01"
      url "https://github.com/trentas/vmstat-macos/releases/download/v#{version}/vmstat-macos_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5647cd4d9e6b014422089be61fe53f114618f999c8b5b30ea6b314f3e0b13db7"
      url "https://github.com/trentas/vmstat-macos/releases/download/v#{version}/vmstat-macos_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "vmstat-macos"
  desc "Linux's vmstat for macOS, sourced from Mach, libproc and IOKit"
  homepage "https://github.com/trentas/vmstat-macos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vmstat"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vmstat"]
    end
  end

  # No zap stanza required

end
