# This file was generated by GoReleaser. DO NOT EDIT.
cask "vmstat-macos" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "1054ad9f22ed9159ecd6f2c091e295d6c273524a493eb322753911da547983ee"
      url "https://github.com/trentas/vmstat-macos/releases/download/v#{version}/vmstat-macos_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fb68f0793b80d5e7099bac8f1d94104079098dcf28b63133f8882c96da367e58"
      url "https://github.com/trentas/vmstat-macos/releases/download/v#{version}/vmstat-macos_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "vmstat-macos"
  desc "Linux's vmstat for macOS, sourced from Mach, libproc and IOKit"
  homepage "https://github.com/trentas/vmstat-macos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vmstat"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vmstat"]
    end
  end

  # No zap stanza required

end
